field: fbdf3e6b-f09a-4707-b299-3b9145e7ddf8 # Rates Footnotes
fieldLayouts:
  7e867343-ac0c-46d2-888d-b0611613c3e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 683e2335-935b-4dc5-b783-616901ccc493 # Footnote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 890bb7a0-6ee1-451b-96cb-d56a91dee8b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: faa4bacc-b4d4-464f-967c-39cad4a89ede
        userCondition: null
fields:
  683e2335-935b-4dc5-b783-616901ccc493: # Footnote
    columnSuffix: ahcvolui
    contentColumnType: text
    fieldGroup: null
    handle: footnote
    instructions: null
    name: Footnote
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: footnote
name: Footnote
sortOrder: 1
